#!/bin/sh /etc/rc.common

START=50

USE_PROCD=1
NAME=uwsd
PROG=/usr/sbin/uwsd

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" --config /etc/uwsd/conf.d/ --log-priority warn --log-channel global --log-channel http --log-channel ws --log-channel script --log-channel ssl
	procd_set_param respawn
	procd_set_param stderr 1

	for file in /etc/uwsd/conf.d/*.conf; do
		if [ -f "$file" ]; then
			procd_set_param file "$file"
		fi
	done

	procd_close_instance
}
