include $(TOPDIR)/rules.mk

PKG_NAME:=luci-plugin-csp

LUCI_TITLE:=LuCI Plugins - Content-Security-Policy HTTP Header plugin
LUCI_DEPENDS:=+luci-base +luci-mod-system

LUCI_TYPE:=plugin

PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
